version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: livros_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_container
    restart: always
    depends_on:
      - db
    environment:
      DB_DATABASE: livros_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  postgres_data:
